import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideDashBoard from "@/components/sideDashboard/sideDashBoard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const fetchedData = await fetch(
  //   "https://21ee-2409-4073-2eb0-5ccc-145c-43c8-a751-7de1.ngrok-free.app/api/chat/?page=1&limit=10",
  //   { cache: "no-cache" }
  // );
  // const data = await fetchedData.json();
  // const sideBarData = data.data;
  // console.log(data.data);

  return (
    <html lang="en">
      <body className="bg-bgImage bg-fixed bg-no-repeat bg-cover">
        {/* {
          <div>
            <SideDashBoard item={sideBarData} />
          </div>
        } */}
        {/* {sideBarData.map((item: any) => (
          <div key={item.id}>
            
            
            <SideDashBoard item={item} />
          </div>
        ))} */}
        {children}
      </body>
    </html>
  );
}
