FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/abewley/sort.git

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]